apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-2nsz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-2nsz
    app.kubernetes.io/part-of: sample-app
  name: devfile-sample-go-basic-2nsz
  namespace: mreid1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-2nsz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-2nsz
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:ecfc7628c49e2e03a0a31062eac45d227f39697b41a4a4df741de06dc33f5109
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
